#
#  Author: Hari Sekhon
#  Date: 2022-08-18 12:31:45 +0100 (Thu, 18 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint:k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#             E l a s t i c   C l o u d   o n   K u b e r n e t e s
# ============================================================================ #

# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: elastic-system

resources:
  - https://download.elastic.co/downloads/eck/2.3.0/crds.yaml
  - https://download.elastic.co/downloads/eck/2.3.0/operator.yaml

#patches:
#  # XXX: remove the caBundle field from ValidatingWebhookConfiguration to prevent it being repeatedly overwritten with the stub 'Cg=='
#         unfortunately this results in a diff that indicates it would remove the caBundle field entirely
#  - path: elastic-cloud-validatingwebhook-delete-cabundle.jsonpatch.yaml
#    target:
#      kind: ValidatingWebhookConfiguration
