#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2022-08-13 09:54:19 +0100 (Sat, 13 Aug 2022)
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Kustomize Objects Namespaced

on:
  push:
    branches:
      - master
    paths:
      - '*.yaml'
      - .github/workflows/kustomize-objects-namespaces.yaml
      - .github/actions/install-kustomize/action.yaml
      - .github/actions/kustomizations-install/action.yaml
  pull_request:
    branches:
      - master
    paths:
      - '*.yaml'
      - .github/workflows/kustomize-objects-namespaces.yaml
      - .github/actions/install-kustomize/action.yaml
      - .github/actions/kustomizations-install/action.yaml
  workflow_dispatch:  # needs to be in default branch before you get the UI option to manually run though
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

env:
  IGNORE_REGEX: 'eks'
  DEBUG: ${{ github.event.inputs.debug == true || '' }}

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  kustomize-check-objects-namespaced:
    name: Kustomize Check Objects Namespaced
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: HariSekhon/DevOps-Bash-tools
          ref: master
          submodules: 'true'  # requires Git 2.18+ to be installed first
          path: bash-tools

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      #- name: Install Kind
      #  run: wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-linux-amd64

      #- name: Kind Version
      #  run: kind version
      #- name: Generate $KUBE_CONFIG
      #  run: |
      #    KUBECONFIG="$(kind get kubeconfig-path)"
      #    echo "KUBECONFIG=$KUBECONFIG" >> "$GITHUB_ENV"

      - name: Cluster Info
        run: kubectl cluster-info

      - name: Install yq
        #run: sudo apt-get install -y yq
        run: sudo snap install yq

      - name: yq version
        run: yq --version

      - uses: ./.github/actions/install-kustomize

      - uses: ./.github/actions/kustomizations-install

      - name: Check Objects are Explicitly Namespaced
        run: |
          if [ -n "${DEBUG:-}" ]; then
            set -x
          fi
          for kustomization in *-kustomization.yaml; do
            if [[ "$kustomization" =~ ^($IGNORE_REGEX)- ]]; then
              echo "Skipping $kustomization"
              echo
              continue
            fi
            echo "$kustomization"
            cp -fv -- "$kustomization" kustomization.yaml
            bash-tools/kustomize_check_objects_namespaced.sh
            echo
          done
